project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description: "Course Projects for STA 9750 at Baruch College"
  site-url: "https://tylerml71.github.io/STA9750-2025-FALL/"
  navbar:
    left:
      - href: mp01.qmd
        text: "Mini-Project #01"
      - href: mp02.qmd
        text: "Mini-Project #02"
      - href: mp03.qmd
        text: "Mini-Project #03"
      - href: mp04.qmd
        text: "Mini-Project #04"
      - href: slides/NYC_Trees_Tyler_Lara.html

    background: primary
    search: false
format:
  html:
    theme: pulse
    toc: false

editor:
  mode: source